# Generated by Django 4.0.1 on 2022-06-09 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookie_stands', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cookiestand',
            name='totalCookies',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='cookiestand',
            name='totalCookies',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
